### PR TITLE
fix: pass recipe dir and config file to inspect explicitly

### LINKED ISSUE #2086: remove recipe_dir and variant being None in `get_built_distribution_names_and_subdirs`
We need to pass these in instead of inferring them. This will need a PR on smithy.

cc @isuruf

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Added a ``news`` entry
* [x] Regenerated schema JSON if schema altered (`python conda_smithy/schema.py`)

closes #2086

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge/core this one is ready for review!

cc @isuruf

**Review by isuruf — APPROVED** [review]

File: conda_smithy/templates/build_steps.sh.tmpl [hunk 1]
```diff
@@ -127,7 +127,7 @@ else
     ( startgroup "Inspecting artifacts" ) 2> /dev/null
 
     # inspect_artifacts was only added in conda-forge-ci-setup 4.6.0
-    command -v inspect_artifacts >/dev/null 2>&1 && inspect_artifacts || echo "inspect_artifacts needs conda-forge-ci-setup >=4.6.0"
+    command -v inspect_artifacts >/dev/null 2>&1 && inspect_artifacts "${RECIPE_ROOT}" -m "${CONFIG_FILE}" || echo "inspect_artifacts needs conda-forge-ci-setup >=4.6.0"
```
Comment (isuruf) [inline conda_smithy/templates/build_steps.sh.tmpl:130]: The version here might need to be updated
